# Generated by Django 3.0.3 on 2020-02-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavepool', '0002_add_source_to_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_cover_story',
            field=models.BooleanField(default=False),
        ),
    ]
