# Generated by Django 3.0.3 on 2020-02-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wavepool', '0003_add_cover_story_prop'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('user_story', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.TextField(max_length=3000)),
                ('UserStory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wavepool.UserStory')),
            ],
        ),
    ]
