# Generated by Django 3.0.3 on 2020-02-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavepool', '0005_add_pubdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='user_story',
            new_name='description',
        ),
    ]
